plugins:
  - jekyll-avatar
  - jekyll-include-cache

remote_theme: hydecorp/hydejack@v9.2.1
theme: jekyll-remote-theme
accent_image: /assets/fond_sid.png
title: Brent_Hackiyaz's World !
description: Welcome to the the blog that see hacking larger than life itself !
font:         'Jersey 15', cursive
font_heading: 'Jersey 15', cursive
google_fonts: Jersey+15
author:
  picture: /assets/fond_sid.png
  social:
    github:  brenthackiyaz
    linkedin: https://fr.linkedin.com/in/solal-stark/
