remote_theme: hydecorp/hydejack@v9.1.4
theme: jekyll-remote-theme
accent_image: /assets/fond_sid.png
title: Brent_Hackiyaz's World !
description: Welcome to the the blog that see hacking larger than life itself !
google_fonts: Jersey+15:400
